### ISSUE TITLE
What is the image

### ISSUE THREAD

**Issue by lostinblue** [atmanos/atmanos#35]
I'm looking through this project becuase I'm working on something similar and seeing where there is overlap, but I don't understand which unikernel is being used. I had been considering u-root since it setting up a Go environment with a very thin layer, it may work well for your project.

**Comment by bernerdschaefer** [comment]
Hello! Thanks for reaching out. AtmanOS does not use an external unikernel as its base.

AtmanOS has its own unikernel, implemented in Go in `src/runtime`. For example, [here's where AtmanOS sets up console, memory managements, and events](https://github.com/atmanos/atmanos/blob/master/src/runtime/sys_atman.go#L122).
